### PR TITLE
Add Python 3.11

### PR DESCRIPTION
**Pull request by Dreamsorcerer**

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
@webknjaz If you could check the CI config here, that'd be great.

Appears that the docs step failing results in the check step being skipped, which is enough to consider the CI as passed.
So, dependabot has been merging broken PRs.

**Comment by Dreamsorcerer** [comment]
Looks like the breakage is caused by one of our libraries. But, doesn't look like anything (tests, deploy...) is setup on that repo:
https://github.com/aio-libs/sphinxcontrib-asyncio/pull/13

**Comment by webknjaz** [comment]
@Dreamsorcerer yes, the check job is broken — it doesn't use my alls-green action so skips are interpreted as passed. Would you integrate it?

**Comment by webknjaz** [comment]
As for sphinxcontrib-asyncio, I wonder if that project is still relevant. Maybe, modern Sphinx already implements that stuff? Looks like it hasn't been released for 7 years, that predates GHA.

**Comment by Dreamsorcerer** [comment]
How does the build for RTD work? Appears it's trying to use Python 3.7 currently. That needs to be bumped up as it's not supported by Sphinx anymore.

**Comment by webknjaz** [comment]
There's some web UI settings. But I don't know what's set up — I don't have access.
I'd recommend adding a YAML config into the repo and it'll supersede those.

**Pull request merged**
