### PR TITLE
Use AppKey in aiohttp 3.9

### PR DESCRIPTION
**Pull request by JCHacking**
I upgrade aiohttp to version 3.9, which requires changing the AppKey usage.

### CODE REVIEW

**Comment by JCHacking** [comment]
I see you have installed aiohttp 3.8.1 instead of 3.9.0b1
I modified it in setup.cfg > line 53
Maybe it needs to be changed somewhere else?

**Comment by Dreamsorcerer** [comment]
Setup seems a little odd on this repo, there's no pinned version in the requirements file. Should sort itself out when 3.9 is a stable release, so this is probably fine.

**Comment by JCHacking** [comment]
> I see you have installed aiohttp 3.8.1 instead of 3.9.0b1 I modified it in setup.cfg > line 53 Maybe it needs to be changed somewhere else?

I see that this version is installed because in requirements/ci.txt is pytest-aiohttp==1.0.5 which must have the aiohttp 3.8.1 dependency version.

I understand that pytest-aiohttp is not up to date, so once the new version is released you will have to update that line to make it work.

I think that in this case the ideal thing would be to wait for aiohttp stable to be able to update the dependencies well.

**Comment by Dreamsorcerer** [comment]
> I see that this version is installed because in requirements/ci.txt is pytest-aiohttp==1.0.5 which must have the aiohttp 3.8.1 dependency version.

That's a minimum bound, it installed the latest stable version: https://github.com/aio-libs/aiojobs/actions/runs/6836361766/job/18591186408?pr=460#step:4:111

**Comment by JCHacking** [comment]
And putting in requirements.txt >=3.9.0b1 would be ok? Or would this make that in the future if there is any beta I choose it instead of just using stable versions?

**Comment by Dreamsorcerer** [comment]
I'll just retry the CI once 3.9 is released, it should pass then. Mainly I just want to have the PRs lined up, so I can release them all in a day or weekend. Normally, we'd have all dependencies pinned in the requirements file (https://github.com/aio-libs/aiohttp-jinja2/blob/master/requirements.txt), but that's a task for a different PR.

**Pull request merged**
