### PR TITLE
Fix deprecation warnings from asyncio on Python 3.8

### PR DESCRIPTION
**Pull request by danpalmer**
## What do these changes do?

- Introduces CI for Python 3.8.
- Fixes deprecation warnings on Python 3.8.
- Deprecates the `loop` argument to `Scheduler` in the same way, providing a fallback.

Design follows suggestion given in #137, as far as I understand it.

## Are there changes in behavior for the user?

Hopefully no. This _does_ change the structure of data stored on the `aiohttp.web.Application`, but given the API functions provided in `aiojobs.aiohttp` I believe this structure to be a private API so ok to change.

## Related issue number

#137 

## Checklist

- [x] I think the code is well written
   - Open to feedback, some duplication that could be avoided for example, depending on maintainer's opinion.
- [ ] Unit tests for the changes exist
   - Not sure about the testing strategy for warnings, but otherwise tests updated
- [x] Documentation reflects the changes
   - The `loop` parameter is not mentioned in the docs.
- [x] Add a new news fragment into the `CHANGES` folder

### CODE REVIEW

**Comment by danpalmer** [comment]
@asvetlov Hi, I'd appreciate a review on this. It's not fully working and I'm not quite sure why. When running the tests they claim there's no running event loop, but I've tried explicitly setting a loop and that doesn't seem to work.

Any advice or review of the general approach would be greatly appreciated.

**Comment by nolar** [comment]
Hello, @danpalmer, @asvetlov.

Is there any progress on this? Python 3.10 is scheduled to be released in less than a month (2021-10-04) — and it removes the `loop=` kwarg to most of asyncio functions and primitives; so, it will not be just a warning (as it was since 3.8), but an error.

If needed, I can post my own PR with 3.10 compatibility (similar to this one, though slightly different; all tests are passing in 3.10). But it is a breaking change anyway (for those who specified `loop=` explicitly).

**Comment by alrusdi** [comment]
Hi @nolar do you have a working variant of aiojobs for 3.10? I didn't find it in your public repos.

**Comment by nolar** [comment]
@alrusdi No, sorry, I didn’t push the changes. There were some issues, and I decided not to continue on this fix, and made my own fire-and-forget scheduler — less capable and less generic but sufficient for my needs: https://github.com/nolar/kopf/pull/835

**Comment by asvetlov** [comment]
Thanks for the PR.
The master branch supports Python 3.8-3.10 now

**Pull request closed without merging**
