### PR TITLE
Make aiohttp as extra requirement

### PR DESCRIPTION
**Pull request by kxepal**
This solves #53

### CODE REVIEW

**Comment by asvetlov** [comment]
thanks!

**Comment by madkote** [comment]
@asvetlov can we merge?

**Comment by madkote** [comment]
any updates here?

**Comment by asvetlov** [comment]
Merged on Apr 7 of 2020.

**Comment by madkote** [comment]
I noticed. Thanks. But is it possible to release it? as `0.2.3` ?

**Comment by asvetlov** [comment]
Let's see if the release pipeline still works :)

**Comment by asvetlov** [comment]
Uploaded. Ironically, travis credits ware run out during the procedure.
The project definitely needs migration to GitHub actions

**Comment by madkote** [comment]
thanks @asvetlov !

**Pull request merged**
