### PR TITLE
Allow providing an external loop for scheduler

### PR DESCRIPTION
**Pull request by livercat**
Currently scheduler is created on the loop from asyncio.get_event_loop(), without an ability to customize it.
This PR adds an ability to pass in an external loop.

### CODE REVIEW

**Comment by asvetlov** [comment]
Why do you want it?
`aiojobs` requires Python >= 3.5.3

**Comment by livercat** [comment]
To add an ability to use single loop in a multithreaded environment, without a need to explicitly call asyncio.set_event_loop()

**Comment by asvetlov** [comment]
I don't follow.
Could you provide an example?

**Comment by livercat** [comment]
While creating an example, I've realized that to create another scheduler in a child thread, we need to use loop.create_task() anyway, which automatically provides that loop to the task.
So the only use-case for the external loop would be if an app uses multiple event loops, which sounds pretty contrived.
Please feel free to close this PR if you think it doesn't worth the effort.

thank you.

**Comment by asvetlov** [comment]
Bingo!
I designed the library carefully to avoid misusages, providing `create_scheduler` async function as the only public API and hiding `Scheduler` constructor pursuits this goal.

**Pull request closed without merging**
